### PR TITLE
New layouts and multiple resizer added

### LINKED ISSUE #5: Allow use different layouts panel for editor 📐
Put a bar with some buttons to change the layout of the editor like Liveweave.

CleanShot 2021-08-09 at 21 06 33@2x

### LINKED ISSUE #16: Add bottom bar to handle editors configuration, layouts and copy to clipboard.

### LINKED ISSUE #34: Allow editors vertical and horizontal resizing at same time
Now, codi.link can only resize vertically or horizontally its editors. To improve the UX, it would be nice do this by positioning the mouse in the middle and resize all the editors at same time, similar as vscode does:

codilink-resize

image

### LINKED ISSUE #139: Add more layouts options
Based on layouts presented in #91, we could add those new layouts to the new settings so we have more options available than the actual 4. Also, these new layouts are nice as they mimic Codepen.

### PR DESCRIPTION
**Pull request by stylessh**
- [x] Layout settings to change the editor view.
- [x] Layout settings are stored on local storage, among the other ones.
- [x] Multiple resizer added.

Keep using split grid.

CLOSED #5 
CLOSED #16
CLOSED #34 
CLOSED #139

### CODE REVIEW

**Comment by eliutgon** [comment]
@stylessh nice work!
I've been testing and there are a few bugs... this is one of them
image

**Comment by stylessh** [comment]
> @stylessh nice work! I've been testing and there are a few bugs... this is one of them image

Could you tell me how this bug happened?

**Comment by eliutgon** [comment]
> > @stylessh nice work! I've been testing and there are a few bugs... this is one of them image
> 
> Could you tell me how this bug happened?

Occurs when you move the gutter and change to another layout.

**Comment by stylessh** [comment]
I'll see what's going on, thanks!

**Comment by stylessh** [comment]
Bug solved. are the more of them?

**Comment by eliutgon** [comment]
> Bug solved. Are the more of them?

Todo bien!

**Comment by stylessh** [comment]
@midudev new layouts are available, no conflicts.

**Pull request closed without merging**
